### ISSUE TITLE
validation for time extraction

### ISSUE THREAD

**Issue by r-luo** [KartRider-Rush-Synergy/weekly-time-attack-calculator#7]
validation for:
1. invalid time (e.g. 01:65:00)
2. unrealistic time (e.g. 10s faster than pro tier, or 1 min slower than Amateur

**Comment by jasonf7** [comment]
1. Already done
2. I'll make a separate ticket for this and close this one

**Comment by jasonf7** [comment]
(2) is a duplicate of #15
